#!/bin/bash --noprofile

apt-get -y install apache2

rm -rf /srv/www
mkdir /srv/www
cp -r /var/www /srv/www/docroot

sed -i -e 's/\/var\/www/\/srv\/www\/docroot/' /etc/apache2/sites-available/default

a2enmod rewrite
a2enmod proxy
a2enmod proxy_http

service apache2 start
