#!/bin/bash --noprofile

serverName=$1

apt-get -y install apache2

rm -rf /srv/www
mkdir /srv/www
cp -r /var/www /srv/www/docroot
sed -i -e 's/\/var\/www/\/srv\/www\/docroot/' /etc/apache2/sites-available/default

cat > /etc/apache2/sites-available/default <<EOF
<VirtualHost *:80>
  ServerAdmin webmaster@localhost
  ServerName $serverName

  DocumentRoot /srv/www/docroot
  <Directory />
    Options FollowSymLinks
    AllowOverride All
  </Directory>

  <Directory /srv/www/docroot/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
  </Directory>

  Alias /js /srv/www/dist/js
  Alias /css /srv/www/dist/css
  Alias /aux /srv/www/aux

  ErrorLog /var/log/apache2/error.log
  LogLevel warn
  CustomLog /var/log/apache2/access.log combined
</VirtualHost>
EOF

a2enmod rewrite
a2enmod proxy
a2enmod proxy_http

service apache2 start
