#!/bin/bash

apt-get install -y python-pip
pip install awscli

cat >> ~/.bashrc <<EOF
AWS_ACCESS_KEY=`cat /vagrant-aws/keys.json | jq -r .access_key_id`
export AWS_ACCESS_KEY
AWS_SECRET_KEY=`cat /vagrant-aws/keys.json | jq -r .secret_access_key`
export AWS_SECRET_KEY
AWS_PRIVATE_KEY_PATH=/vagrant-aws/bill-boyer.com.pem.txt
export AWS_PRIVATE_KEY_PATH
EOF
