#!/bin/bash --noprofile

user=$1
homeDir=$2

cat >> $homeDir/.profile <<EOF
export AWS_ACCESS_KEY=`cat /vagrant-aws/keys.json | jq -r .access_key_id`
export AWS_SECRET_KEY=`cat /vagrant-aws/keys.json | jq -r .secret_access_key`
export AWS_PRIVATE_KEY_PATH=/vagrant-aws/bill-boyer.com.pem.txt
export AWS_CONFIG_FILE=$HOME/.aws-config
EOF
chown $user $homeDir/.profile
chmod 600 $homeDir/.profile

cat >> $homeDir/.aws-config <<EOF
[default]
aws_access_key_id = `cat /vagrant-aws/keys.json | jq -r .access_key_id`
aws_secret_access_key = `cat /vagrant-aws/keys.json | jq -r .secret_access_key`
region = us-west-2
EOF
chown $user $homeDir/.aws-config
chmod 600 $homeDir/.aws-config
