#!/bin/bash --noprofile

if [ $# != 1 ] ;
then
	echo "Usage: base <path to ops>"
	exit 1
fi

ops=$1

sleep 60

/bin/rm -f /var/lib/apt/lists/lock 
/bin/rm -f /var/cache/apt/archives/lock
/bin/rm -f /var/lib/dpkg/lock
sudo dpkg --configure -a
sudo apt-get -f install

apt-get -y update
apt-get install -y dos2unix
apt-get install -y rsync
apt-get install -y unzip
apt-get install -y curl

cd /usr/local/bin
wget -nv http://stedolan.github.io/jq/download/linux64/jq
chmod +x jq

cat >> ~/.profile <<EOF
alias rmt='rm -f *~'
alias h='history'
export OPS=$ops
EOF
