#!/bin/bash --noprofile

if [ $# != 1 ] ;
then
	echo "Usage: jenkins <password>"
	exit 1
fi

password=$1

apt-get -y install jenkins
echo 'jenkins ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
sleep 30

sed -i -e "s/JENKINS_ARGS=\"--webroot=\$JENKINS_RUN\/war --httpPort=\$HTTP_PORT --ajp13Port=\$AJP_PORT --preferredClassLoader=java.net.URLClassLoader\"/JENKINS_ARGS=\"--webroot=\$JENKINS_RUN\/war --httpPort=\$HTTP_PORT --ajp13Port=\$AJP_PORT --preferredClassLoader=java.net.URLClassLoader --argumentsRealm.admin=admin --argumentsRealm.passwd.admin=$password\"/" /etc/default/jenkins

java -jar /usr/share/jenkins/cli/java/cli.jar -s http://localhost:8080/ safe-restart
sleep 30
