#!/bin/bash --noprofile

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10

cat > /etc/apt/sources.list.d/mongodb.list <<EOF
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
EOF

apt-get -y update

sudo apt-get install mongodb-10gen
npm install -g mongodb
