#!/bin/bash --noprofile

apt-get update -y
apt-get install -y python-software-properties python g++ make
add-apt-repository -y ppa:chris-lea/node.js
apt-get update -y
apt-get install -y nodejs
npm install -g express
