#!/bin/bash --noprofile

cd /tmp
mkdir node
cd node

wget -nv http://nodejs.org/dist/v0.10.24/node-v0.10.24-linux-x64.tar.gz
gunzip < node-v0.10.24-linux-x64.tar.gz | tar xvf -
mv node-v0.10.24-linux-x64 /usr/local

# use Upstart instead

cat >> /etc/init.d/node.js.rc <<EOF
#!/bin/bash
DIR=/var/www/YOUR_APP_NAME
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NODE_PATH=/usr/local/lib/node_modules

case $1 in
   start)
      nohup "node" "$DIR/proxy.js" 1>>"$DIR/logs/proxy.log" 2>&1 &
      echo $! > "$DIR/pids/proxy.pid";
      ;;
    stop)
      kill `cat $DIR/pids/proxy.pid` ;;
    *)
      echo "usage: /etc/init.d/http-proxy {start|stop}" ;;
esac
exit 0
EOF
