#!/bin/bash --noprofile

if [ $# != 1 ] ;
then
	echo "Usage: passenger <app>"
	exit 1
fi

app=$1

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
apt-get -y install apt-transport-https

cat > /etc/apt/sources.list.d/passenger.list <<EOF
deb https://oss-binaries.phusionpassenger.com/apt/passenger precise main
EOF

apt-get -y update

gem install passenger --no-document

cat > /etc/rc.local <<EOF
#!/bin/sh

cd /srv/rails/$app
passenger stop --port 81 --pid-file /tmp/passenger.81.pid
RAILS_ENV=production passenger start --daemonize --port 81 --pid-file /tmp/passenger.81.pid

exit 0
EOF

chmod +x /etc/rc.local

mkdir /srv/rails
cd /srv/rails
rails new $app -f
cd $app
/etc/rc.local
