#!/bin/bash --noprofile

apt-get install -y libssl-dev
apt-get install -y libreadline-dev
apt-get install -y zlib1g-dev

cd /tmp
/bin/rm -rf ruby
mkdir ruby
cd ruby

wget -nv http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.1.tar.gz
gunzip < ruby-2.1.1.tar.gz | tar xf -
cd ruby-2.1.1
./configure --prefix=/usr
make
make install

gem install unf --no-document
gem install iconv --no-document
