#!/bin/bash --noprofile

cd /tmp
/bin/rm -rf sqlite-autoconf-3080401
wget -nv https://www.sqlite.org/2014/sqlite-autoconf-3080401.tar.gz
gunzip < sqlite-autoconf-3080401.tar.gz | tar xvf -
cd sqlite-autoconf-3080401
./configure
make
make install
cd /usr/lib/x86_64-linux-gnu/
/bin/rm -f libsqlite*
cp /usr/local/lib/libsqlite3.so.0.8.6 .
ln -s libsqlite3.so.0.8.6 libsqlite3.so.0
ln -s libsqlite3.so.0.8.6 libsqlite3.so
