#!/bin/bash --noprofile

wget -nv http://files.vagrantup.com/packages/a40522f5fabccb9ddabad03d836e120ff5d14093/vagrant_1.3.5_x86_64.deb
dpkg -i vagrant_1.3.5_x86_64.deb
vagrant plugin install vagrant-aws
