#!/bin/bash --noprofile

apt-get -y install apache2

rm -rf /srv/www
mkdir /srv/www
cp -r /var/www /srv/www/htdocs
sed -i -e 's/\/var\/www/\/srv\/www\/htdocs/' /etc/apache2/sites-available/default

exit 0

cat > /etc/apache2/sites-available/default <<EOF
<VirtualHost *:80>
  ServerAdmin webmaster@localhost
  ServerName www.bill-boyer.com

  DocumentRoot /srv/www/htdocs
  <Directory />
    Options FollowSymLinks
    AllowOverride None
  </Directory>

  <Directory /srv/www/htdocs/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    allow from all
  </Directory>

  ErrorLog /var/log/apache2/error.log
  LogLevel warn
  CustomLog /var/log/apache2/access.log combined
</VirtualHost>
EOF

cat > /etc/apache2/sites-available/vanity <<EOF
<VirtualHost *:80>
  ServerName bill-boyer.com
  ServerAlias *.bill-boyer.com william-boyer.com *.william-boyer.com
  Redirect permanent / http://www.bill-boyer.com/
</VirtualHost>
EOF
a2ensite vanity

service apache2 restart

apt-get -y install sqlite3
apt-get -y install libsqlite3-ruby
gem install sqlite3-ruby

apt-get -y install rails

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
apt-get -y install apt-transport-https

cat > /etc/apt/sources.list.d/passenger.list <<EOF
deb https://oss-binaries.phusionpassenger.com/apt/passenger precise main
EOF

apt-get -y update

apt-get -y install passenger
gem install passenger

cat > /etc/rc.local <<EOF
#!/bin/sh -e
passenger start --daemonize --port 81
exit 0
EOF

mkdir ~/apps
cd ~/apps
rails main
cd main
passenger start --daemonize --port 81

gem install sass

echo NOW REMEMBER TO RUN ./deploy\!\!\!
