#!/bin/bash

tmp=`mktemp /tmp/tmp.XXXXXXXXXX`

for arg in $@
do
  find $arg -type f -not -name '*~' -exec cat {} >> $tmp \;
done

hash=`cat $tmp | /usr/bin/openssl md5 | sed -e 's/.* //'`

echo -n $hash

rm -f $tmp
