#!/bin/bash

file=$1
backupDir='s3:/'$2

s3='aws s3 --endpoint-url https://s3.amazonaws.com'

tmp=`mktemp`
$s3 cp ${backupDir}/latest $tmp
backupFile=`cat $tmp`
/bin/rm $tmp

$s3 cp $backupFile $file
