#!/bin/bash

path=/vagrant-mnt/ops/scripts/provision/ubuntu

$path/base ops.bill-boyer.com live
$path/ruby
$path/jenkins
$path/aws
$path/vagrant
$path/node
$path/grunt

$path/aws-user root root /root

sudo -u jenkins $path/jenkins-user /vagrant/jobs
