#!/bin/bash --noprofile

for f in ./*
do
  echo Running test "$f"...
  ./$f
  if [ $? == 0 ]; then
    echo "...success.";
  else
    echo "...failure.";
	/vagrant-scripts/aws/notify "Test $f failed."
    exit 1;
  fi
done

exit 0
