#!/bin/bash -ex

dir=$1

for file in $dir/*
do
  echo Running test "$file"...
  $file "$@"
  if [ $? == 0 ]; then
    echo "...success."
  else
    echo "...failure."
	/vagrant-mnt/ops/scripts/infrastructure/aws/notify "Test $file failed."
    exit 1
  fi
done
