#!/bin/bash --noprofile

dir=ARGV[0]

for f in $dir/*
do
  echo Running test "$f"...
  $dir/$f
  if [ $? == 0 ]; then
    echo "...success.";
  else
    echo "...failure.";
	/vagrant-scripts/infrastructure/aws/notify "Test $f failed."
    exit 1;
  fi
done

exit 0
